name = "tg-image"
compatibility_date = "2023-01-01"
main = "src/index.js"

[vars]
# 可以在这里设置默认环境变量
TG_Bot_Token = ""
TG_Chat_ID = ""
JWT_SECRET = ""

# 注意：在部署前，请先创建这些 KV 命名空间，并将生成的 ID 填入下面的配置中
# 使用以下命令创建 KV 命名空间（Wrangler 4.x 版本）：
# npx wrangler kv namespace create "tg-image_img_url"
# npx wrangler kv namespace create "tg-image_users"
#
# 或者使用 npm run create-kv 命令自动创建 KV 命名空间并更新配置

[[kv_namespaces]]
binding = "img_url"
id = "1b6c579440fc4f278382454d82ab68f9"

[[kv_namespaces]]
binding = "users"
id = "a6d8ce8b4ffe4897b82c555dc1e5a9cf"

[site]
bucket = "./public"
